version: '3.9'

services:
  web:
    build: .
    container_name: colorpalette-web
    ports:
      - "5000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
